WITH CTE AS
(
select 

TO_TIMESTAMP(STARTED_AT) as STARTED_AT,
DATE(TO_TIMESTAMP(STARTED_AT)) as DATE_STARTED_AT,
HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
MONTH(TO_TIMESTAMP(STARTED_AT)) as MONTH_STARTED_AT,
YEAR(TO_TIMESTAMP(STARTED_AT)) as YEAR_STARTED_AT,
DAYNAME(TO_TIMESTAMP(STARTED_AT)) as DAY_STARTED_AT,

{{get_date_type('STARTED_AT')}} AS DAY_TYPE,

{{get_season('STARTED_AT')}} as STATION_OF_YEAR


from {{ source('demo', 'bike') }}
where STARTED_AT != 'started_at'
)

select *
from CTE